application: 
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /posts/new
  script: blog.py
  login: admin

- url: /posts/edit/.*
  script: blog.py
  login: admin

- url: .*
  script: blog.py
